# Generated by Django 2.1.4 on 2019-09-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('table', 'Table'), ('chair', 'Chair')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='')),
                ('dt', models.DateTimeField()),
                ('author', models.CharField(max_length=32)),
                ('ver', models.CharField(max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Сomposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.PositiveSmallIntegerField()),
                ('part', models.CharField(max_length=32)),
                ('def_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Finish')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.Model')),
            ],
        ),
    ]
