# Generated by Django 2.1.4 on 2019-09-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190917_1511'),
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='сomposition',
            name='allowed_mats',
            field=models.ManyToManyField(to='material.Type'),
        ),
        migrations.AddField(
            model_name='сomposition',
            name='part_displayname',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='сomposition',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.Part'),
        ),
    ]
