# Generated by Django 2.1.4 on 2019-09-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_auto_20190917_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prefix',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
