# Generated by Django 2.1.4 on 2019-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_item_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
