# Generated by Django 2.1.4 on 2019-10-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20191001_1254'),
        ('furniture', '0004_item_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveSmallIntegerField()),
                ('part', models.CharField(choices=[('frame', 'Frame'), ('base', 'Base'), ('edge', 'Edge'), ('tray', 'Tray'), ('hardware', 'Hardware'), ('seat', 'Seat'), ('back', 'Back'), ('arm', 'Arm'), ('top', 'Top'), ('insert1', 'Small Top Insert'), ('insert2', 'Large Top Insert')], max_length=8)),
                ('allowed_mats', models.ManyToManyField(to='material.Type')),
                ('def_mat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Finish')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.Model')),
            ],
        ),
        migrations.RemoveField(
            model_name='сomposition',
            name='allowed_mats',
        ),
        migrations.RemoveField(
            model_name='сomposition',
            name='def_mat',
        ),
        migrations.RemoveField(
            model_name='сomposition',
            name='model',
        ),
        migrations.RemoveField(
            model_name='сomposition',
            name='part',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Сomposition',
        ),
    ]
