# Generated by Django 2.1.4 on 2019-10-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_auto_20191001_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='def_mat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='material.Finish'),
        ),
    ]
