# Generated by Django 2.1.4 on 2019-10-03 13:06

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20191001_1254'),
        ('furniture', '0006_auto_20191002_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='combine_mats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suited', models.CharField(max_length=2048, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.Model')),
                ('texture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Finish')),
            ],
        ),
        migrations.RemoveField(
            model_name='composition',
            name='allowed_mats',
        ),
        migrations.AddField(
            model_name='composition',
            name='allowed_mattypes',
            field=models.ManyToManyField(blank=True, to='material.Type'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='def_mat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.Finish'),
        ),
    ]
