# Generated by Django 2.2.5 on 2019-10-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_auto_20191003_1315'),
        ('furniture', '0008_auto_20191003_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Model3D',
        ),
    ]
