# Generated by Django 2.2.5 on 2019-10-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0009_auto_20191003_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model3d',
            name='author',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='model3d',
            name='ver',
        ),
        migrations.AddField(
            model_name='item',
            name='swatch',
            field=models.ImageField(null=True, upload_to='static/furniture/swatches'),
        ),
    ]
