# Generated by Django 2.2.5 on 2019-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0010_auto_20191004_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='shadow',
            field=models.ImageField(null=True, upload_to='static/furniture/shadows'),
        ),
    ]
