# Generated by Django 2.2.7 on 2019-12-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_colormatch_colormatchingchart'),
        ('furniture', '0012_auto_20191007_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.ColorMatchingChart'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='shadow',
            field=models.ImageField(blank=True, null=True, upload_to='static/furniture/shadows'),
        ),
        migrations.DeleteModel(
            name='CombineMats',
        ),
    ]
