# Generated by Django 3.0 on 2019-12-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20191209_1649'),
        ('furniture', '0014_remove_model3d_shadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='part',
            field=models.CharField(choices=[('frame', 'Frame'), ('base', 'Base'), ('edge', 'Edge'), ('tray', 'Tray'), ('hardware', 'Hardware'), ('seat', 'Seat'), ('back', 'Back'), ('pillow', 'Seat & Back'), ('arm', 'Arm'), ('top', 'Top'), ('insert1', 'Small Top Insert'), ('insert2', 'Large Top Insert')], max_length=8),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frame', 'Frame'), ('base', 'Base'), ('edge', 'Edge'), ('tray', 'Tray'), ('hardware', 'Hardware'), ('seat', 'Seat'), ('back', 'Back'), ('pillow', 'Seat & Back'), ('arm', 'Arm'), ('top', 'Top'), ('insert1', 'Small Top Insert'), ('insert2', 'Large Top Insert')], max_length=8)),
                ('cover', models.ManyToManyField(blank=True, to='material.Type')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.Model3D')),
            ],
        ),
    ]
