# Generated by Django 3.0 on 2019-12-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0016_auto_20191225_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Composition',
        ),
    ]
