# Generated by Django 3.0 on 2020-03-12 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furniture', '0017_delete_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model3d_model_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model3d',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model3d_model_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model3d',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='url',
            field=models.FileField(null=True, upload_to='static/furniture/models'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(choices=[('frame', 'Frame'), ('base', 'Base'), ('edge', 'Edge'), ('tray', 'Tray'), ('rim', 'Rim'), ('hardware', 'Hardware'), ('seat', 'Seat'), ('back', 'Back'), ('pillow', 'Seat & Back'), ('arm', 'Arm'), ('top', 'Top'), ('insert', 'Insert'), ('insert1', 'Small Top Insert'), ('insert2', 'Large Top Insert')], max_length=8),
        ),
    ]
