# Generated by Django 3.0 on 2020-04-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_auto_20200422_1426'),
        ('furniture', '0019_auto_20200422_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='variant',
            new_name='kind',
        ),

        migrations.AddField(
            model_name='part',
            name='defaultFinish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='material.Finish'),
        ),
    ]
