# Generated by Django 3.0 on 2020-04-23 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_auto_20200422_1426'),
        ('furniture', '0021_auto_20200424_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishes', models.ManyToManyField(blank=True, to='material.Finish')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.Part')),
                ('patterns', models.ManyToManyField(blank=True, to='material.Pattern')),
            ],
        ),
    ]
