# Generated by Django 3.0 on 2020-04-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0022_limitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkind',
            name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.Model3D'),
        ),
    ]
