# Generated by Django 3.0 on 2020-05-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_auto_20200422_1426'),
        ('furniture', '0023_auto_20200425_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh',
            name='cover',
            field=models.ManyToManyField(to='material.Nature'),
        ),
        migrations.AlterField(
            model_name='part',
            name='cover',
            field=models.ManyToManyField(to='material.Nature'),
        ),
        migrations.AlterField(
            model_name='part',
            name='defaultFinish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.Finish'),
        ),
        migrations.AlterField(
            model_name='part',
            name='meshes',
            field=models.ManyToManyField(to='furniture.Mesh'),
        ),
        migrations.AlterField(
            model_name='productkind',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
