# Generated by Django 3.0 on 2020-09-28 13:15

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0024_auto_20200504_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesh',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.Model3D'),
        ),
        migrations.AlterField(
            model_name='mesh',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='blend',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/furniture/models/blender'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='glb',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/furniture/models/gltf'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='solidSource',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/furniture/models/sw'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('chair', 'Chair'), ('combo', 'Combination'), ('toy', 'Toy')], max_length=5),
        ),
    ]
