# Generated by Django 3.1 on 2020-10-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0025_auto_20200928_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.productkind'),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.BooleanField(default=False)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.productkind')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.part')),
            ],
        ),
    ]
