# Generated by Django 3.1 on 2020-10-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0026_auto_20201029_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkind',
            name='parts',
        ),
    ]
