# Generated by Django 3.1 on 2020-10-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0027_remove_productkind_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkind',
            name='parts',
            field=models.ManyToManyField(blank=True, through='furniture.Configuration', to='furniture.Part'),
        ),
    ]
