# Generated by Django 3.1 on 2020-10-30 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0028_productkind_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitation',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='limitation',
            name='part',
        ),
        migrations.AddField(
            model_name='configuration',
            name='limitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.limitation'),
        ),
        migrations.AddField(
            model_name='limitation',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
