# Generated by Django 3.1 on 2020-10-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0029_auto_20201030_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesh',
            name='optional',
        ),
    ]
