# Generated by Django 3.1 on 2020-10-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_auto_20201015_2204'),
        ('furniture', '0030_remove_mesh_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='colorChart',
        ),
        migrations.RemoveField(
            model_name='part',
            name='defaultFinish',
        ),
        migrations.AddField(
            model_name='configuration',
            name='colorChart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.colormatchingchart'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='defaultFinish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.finish'),
        ),
        migrations.AddField(
            model_name='part',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='limitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.limitation'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='optional',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
