# Generated by Django 3.1 on 2020-11-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0032_auto_20201108_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkind',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
