# Generated by Django 3.1 on 2020-11-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0033_auto_20201108_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesh',
            name='cover',
        ),
    ]
