# Generated by Django 2.1.4 on 2019-09-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('directory', models.TextField()),
                ('code', models.PositiveIntegerField()),
                ('vendor', models.TextField()),
                ('type', models.TextField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('url', models.FilePathField()),
                ('info', models.TextField()),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('dpi', models.FloatField(default=0)),
                ('ordinal', models.PositiveIntegerField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
