# Generated by Django 2.1.4 on 2019-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='ordinal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
