# Generated by Django 2.1.4 on 2019-09-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190917_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Type'),
        ),
    ]
