# Generated by Django 2.2.5 on 2019-10-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20191001_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='info',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='directory',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='vendor',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
