# Generated by Django 2.2.5 on 2019-10-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_auto_20191015_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='dpi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='texture',
            name='h',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='texture',
            name='w',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
