# Generated by Django 3.0 on 2019-12-09 16:49

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_colormatch_colormatchingchart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormatch',
            name='suited',
            field=models.CharField(max_length=2048, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
