# Generated by Django 2.2.7 on 2019-12-19 16:42

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_auto_20191209_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormatch',
            name='suited',
            field=models.CharField(max_length=2048, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
