# Generated by Django 3.0 on 2020-04-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_auto_20191219_1942'),
    ]

    operations = [
        migrations.RenameModel('Type', 'Nature'),
        migrations.RenameModel('Texture', 'Finish'),
        migrations.RenameField(
            model_name='pattern',
            old_name='type',
            new_name='nature',
        ),
    ]
