# Generated by Django 3.0 on 2020-06-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_auto_20200422_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finish',
            name='color',
            field=models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='finish',
            name='dpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='metalness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='normal',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='ordinal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='roughness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='specular',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='transparency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='url',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='finish',
            name='w',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
