# Generated by Django 3.0 on 2020-09-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_auto_20200607_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('hue', models.FloatField(blank=True, null=True)),
                ('saturation', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diffuse', models.ImageField(blank=True, null=True, upload_to='static/material/finishes')),
                ('roughness', models.ImageField(blank=True, null=True, upload_to='static/material/finishes')),
                ('specular', models.ImageField(blank=True, null=True, upload_to='static/material/finishes')),
                ('normal', models.ImageField(blank=True, null=True, upload_to='static/material/finishes')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('w', models.PositiveIntegerField(blank=True, null=True)),
                ('h', models.PositiveIntegerField(blank=True, null=True)),
                ('dpi', models.FloatField(blank=True, null=True)),
                ('multiplier', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='finish',
            name='color',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='h',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='metalness',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='ordinal',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='roughness',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='specular',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='transparency',
        ),
        migrations.RemoveField(
            model_name='finish',
            name='w',
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('color', models.CharField(blank=True, help_text='HEX color, as #RRGGBB', max_length=7, null=True, verbose_name='Color')),
                ('roughness', models.FloatField(blank=True, null=True)),
                ('specular', models.FloatField(blank=True, null=True)),
                ('metalness', models.FloatField(blank=True, null=True)),
                ('transparency', models.FloatField(blank=True, null=True)),
                ('normalStrength', models.FloatField(blank=True, null=True)),
                ('diffuse_hsv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.HSV')),
            ],
        ),
        migrations.AddField(
            model_name='finish',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.Features'),
        ),
        migrations.AddField(
            model_name='finish',
            name='maps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Maps'),
        ),
        migrations.AddField(
            model_name='finish',
            name='tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Tile'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.Features'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='maps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Maps'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Tile'),
        ),
    ]
