# Generated by Django 3.0 on 2020-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_auto_20200928_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='by',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='copyrights',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='web',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
