# Generated by Django 3.0 on 2020-09-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0016_auto_20200928_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
