# Generated by Django 3.0 on 2020-10-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_maps_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finish',
            name='squ',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
