# Generated by Django 3.1 on 2020-11-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_auto_20201015_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
