# Generated by Django 3.1 on 2020-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0020_auto_20201115_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='diffuse',
            field=models.CharField(blank=True, choices=[('finish', 'finish'), ('pattern', 'pattern')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='normal',
            field=models.CharField(blank=True, choices=[('finish', 'finish'), ('pattern', 'pattern')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='roughness',
            field=models.CharField(blank=True, choices=[('finish', 'finish'), ('pattern', 'pattern')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='maps',
            name='specular',
            field=models.CharField(blank=True, choices=[('finish', 'finish'), ('pattern', 'pattern')], max_length=7, null=True),
        ),
    ]
