# Generated by Django 2.1.4 on 2019-09-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_x', models.PositiveIntegerField()),
                ('size_y', models.PositiveIntegerField()),
                ('focus', models.PositiveIntegerField()),
                ('angles', models.CharField(max_length=64)),
                ('cycles', models.TextField(default='')),
                ('renders_done', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.Model')),
            ],
        ),
    ]
