# Generated by Django 2.1.4 on 2019-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='angles',
            field=models.CharField(default='60,0,0,15', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='focus',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='order',
            name='size_x',
            field=models.PositiveIntegerField(default=1250),
        ),
        migrations.AlterField(
            model_name='order',
            name='size_y',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
