# Generated by Django 2.1.4 on 2019-10-03 13:15

import re

import django.core.validators
import render.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_auto_20191003_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='angles',
            field=models.CharField(default='60,0,0,15', max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='cycles',
            field=models.CharField(default='', max_length=2048, validators=[render.models.validate_cycles]),
        ),
    ]
