# Generated by Django 3.0 on 2019-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_auto_20191210_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='running',
            field=models.BooleanField(null=True),
        ),
    ]
