# Generated by Django 3.0 on 2019-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0008_auto_20191221_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='parts',
        ),
        migrations.AddField(
            model_name='iteration',
            name='parts',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
