# Generated by Django 3.0 on 2019-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0009_auto_20191224_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='N',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
