# Generated by Django 3.0 on 2020-03-24 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0010_order_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shadow',
            field=models.ImageField(null=True, upload_to='static/furniture/shadows/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='angle_0',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-179), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='angle_3',
            field=models.FloatField(default=60, null=True, validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='focus',
            field=models.PositiveIntegerField(default=75, null=True, validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='size_y',
            field=models.PositiveIntegerField(default=15, null=True),
        ),
    ]
