# Generated by Django 3.0 on 2020-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0011_auto_20200324_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size_x',
            field=models.PositiveIntegerField(default=1250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size_y',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
    ]
