# Generated by Django 3.0 on 2020-04-22 11:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_auto_20200422_1410'),
        ('furniture', '0019_auto_20200422_1410'),
        ('render', '0012_auto_20200324_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('orth', models.BooleanField(default=False)),
                ('focus', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(250)])),
                ('phi', models.IntegerField(validators=[django.core.validators.MinValueValidator(-179), django.core.validators.MaxValueValidator(180)])),
                ('teta', models.FloatField(default=60, validators=[django.core.validators.MaxValueValidator(90)])),
                ('r', models.PositiveIntegerField(default=60, null=True)),
                ('lookAt_x', models.FloatField(default=0)),
                ('lookAt_y', models.FloatField(default=0)),
                ('lookAt_z', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples', models.PositiveIntegerField(default=128, null=True, validators=[django.core.validators.MinValueValidator(32), django.core.validators.MaxValueValidator(512)])),
                ('size_x', models.PositiveIntegerField(default=1250, null=True, validators=[django.core.validators.MinValueValidator(128), django.core.validators.MaxValueValidator(2500)])),
                ('size_y', models.PositiveIntegerField(default=1000, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)])),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('world', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='mats',
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='order',
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='N',
        ),
        migrations.RemoveField(
            model_name='order',
            name='angle_0',
        ),
        migrations.RemoveField(
            model_name='order',
            name='angle_3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cycles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size_x',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size_y',
        ),
        migrations.AddField(
            model_name='iteration',
            name='finishes',
            field=models.ManyToManyField(to='material.Finish'),
        ),
        migrations.AddField(
            model_name='iteration',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='iteration',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.Part'),
        ),
        migrations.AddField(
            model_name='iteration',
            name='patterns',
            field=models.ManyToManyField(to='material.Pattern'),
        ),
        migrations.AddField(
            model_name='order',
            name='iterations',
            field=models.ManyToManyField(to='render.Iteration'),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.ProductKind'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shadow',
            field=models.ImageField(null=True, upload_to='static/furniture/models/shadows/'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('rotation_z', models.PositiveIntegerField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('finishesOnParts', models.CharField(default='', max_length=2048)),
                ('scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.Scene')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.ProductKind')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='render.Quality'),
        ),
    ]
