# Generated by Django 3.0 on 2020-04-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0013_auto_20200422_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='variant',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='variant',
            new_name='kind',
        ),
    ]
