# Generated by Django 3.0 on 2020-04-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0015_auto_20200424_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Limitation',
        ),
    ]
