# Generated by Django 3.0 on 2020-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0016_delete_limitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shadow',
            field=models.ImageField(blank=True, null=True, upload_to='static/furniture/models/shadows/'),
        ),
    ]
