# Generated by Django 3.0 on 2020-06-07 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0017_auto_20200504_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='lookAt_x',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='lookAt_y',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='teta',
        ),
        migrations.AddField(
            model_name='camera',
            name='theta',
            field=models.FloatField(default=75, validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='camera',
            name='phi',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-179), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='camera',
            name='r',
            field=models.FloatField(default=6.0, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
