# Generated by Django 3.0 on 2020-06-13 14:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0024_auto_20200504_2345'),
        ('render', '0018_auto_20200607_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='finishesOnParts',
            new_name='finishesOnMeshes',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='kind',
        ),
        migrations.AddField(
            model_name='actor',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='furniture.Model3D'),
        ),
        migrations.AddField(
            model_name='camera',
            name='lookAt_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='lookAt_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.Camera'),
        ),
        migrations.AddField(
            model_name='scene',
            name='img',
            field=models.FileField(null=True, upload_to='scenes/'),
        ),
        migrations.AddField(
            model_name='scene',
            name='quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='render.Quality'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='focus',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='camera',
            name='phi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='theta',
            field=models.FloatField(default=1.4),
        ),
    ]
