# Generated by Django 3.1 on 2020-11-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0019_auto_20200613_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rule',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
