# Generated by Django 3.1 on 2020-11-05 12:39

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0021_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shadow',
        ),
        migrations.AddField(
            model_name='order',
            name='renders_posted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('ready', models.BooleanField(null=True)),
                ('produced', models.PositiveIntegerField(default=0)),
                ('activeOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='render.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.machine'),
        ),
    ]
