# Generated by Django 3.1 on 2020-11-05 17:26

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0022_auto_20201105_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='scene',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.machine'),
        ),
    ]
