# Generated by Django 3.1 on 2020-11-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0024_auto_20201107_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='activeOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.order'),
        ),
    ]
