# Generated by Django 3.1 on 2020-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0025_auto_20201108_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='power',
            field=models.FloatField(default=1),
        ),
    ]
