# Generated by Django 3.1 on 2020-11-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0026_machine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
