# Generated by Django 3.1 on 2020-11-19 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0027_auto_20201111_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='compression',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='rule',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
