# Generated by Django 3.1 on 2020-11-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0028_auto_20201119_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='engine',
            field=models.CharField(choices=[('BLENDER_EEVEE', 'eevee'), ('CYCLES', 'cycles')], default='BLENDER_EEVEE', max_length=13),
        ),
    ]
