# Generated by Django 3.1.4 on 2021-04-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0030_quality_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='primary',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
